<?php // $rootUrl="http://localhost/~bram/github.com/atelierbram/base4tone-prism/src/views/b4t_classic-a/dark/" ?>
<?php // $assetUrl="http://localhost/~bram/github.com/atelierbram/base4tone-prism/" ?>
<?php $rootUrl="https://atelierbram.github.io/base4tone-prism/b4t_classic-a/dark/" ?>
<?php $assetUrl="https://atelierbram.github.io/base4tone-prism/" ?>
<?php $repoUrlMaster="https://github.com/atelierbram/Base4Tone-prism/blob/master/" ?>
