<?php
echo "code[class*='language-'],\n";
echo "pre[class*='language-'] {\n";
echo "  color: $B4T_b0;\n";
echo "  background: none;\n";
echo "  font-family: Consolas, Menlo, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;\n";
echo "  text-align: left;\n";
echo "  white-space: pre;\n";
echo "  word-spacing: normal;\n";
echo "  word-break: normal;\n";
echo "  word-wrap: normal;\n";
echo "  line-height: 1.5;\n";
echo "\n";
echo "  -moz-tab-size: 4;\n";
echo "  -o-tab-size: 4;\n";
echo "  tab-size: 4;\n";
echo "\n";
echo "  -webkit-hyphens: none;\n";
echo "  -moz-hyphens: none;\n";
echo "  -ms-hyphens: none;\n";
echo "  hyphens: none;\n";
echo "}\n";
echo "\n";
echo "pre[class*='language-']::-moz-selection, pre[class*='language-'] ::-moz-selection,\n";
echo "code[class*='language-']::-moz-selection, code[class*='language-'] ::-moz-selection {\n";
echo "  background: $B4T_B20;\n";
echo "}\n";
echo "\n";
echo "pre[class*='language-']::selection, pre[class*='language-'] ::selection,\n";
echo "code[class*='language-']::selection, code[class*='language-'] ::selection {\n";
echo "  background: $B4T_B20;\n";
echo "}\n";
echo "\n";
echo "/* Code blocks */\n";
echo "pre[class*='language-'] {\n";
echo "  padding: 1em;\n";
echo "  margin: .5em 0;\n";
echo "  overflow: auto;\n";
echo "}\n";
echo "\n";
echo ":not(pre) > code[class*='language-'],\n";
echo "pre[class*='language-'] {\n";
echo "  background: $B4T_b23;\n";
echo "}\n";
echo "\n";
echo "/* Inline code */\n";
echo ":not(pre) > code[class*='language-'] {\n";
echo "  padding: .1em;\n";
echo "  border-radius: .3em;\n";
echo "  white-space: normal;\n";
echo "}\n";
echo "\n";
echo ".token.comment,\n";
echo ".token.prolog,\n";
echo ".token.doctype,\n";
echo ".token.cdata {\n";
echo "  color: $B4T_b14;\n";
echo "}\n";
echo "\n";
echo ".token.punctuation {\n";
echo "  color: $B4T_b14;\n";
echo "}\n";
echo "\n";
echo ".namespace {\n";
echo "  opacity: .7;\n";
echo "}\n";
echo "\n";
echo ".token.property,\n";
echo ".token.tag,\n";
echo ".token.boolean,\n";
echo ".token.constant,\n";
echo ".token.symbol,\n";
echo ".token.deleted {\n";
echo "  color: $B4T_C8;\n";
echo "}\n";
echo "\n";
echo ".token.selector,\n";
echo ".token.attr-name,\n";
echo ".token.string,\n";
echo ".token.char,\n";
echo ".token.builtin,\n";
echo ".token.inserted {\n";
echo "  color: $B4T_A7;\n";
echo "}\n";
echo "\n";
echo ".token.id {\n";
echo "  color: $B4T_d7;\n";
echo "}\n";
echo "\n";
echo ".token.operator,\n";
echo ".token.entity,\n";
echo ".token.url,\n";
echo ".language-css .token.string,\n";
echo ".style .token.string {\n";
echo "  color: $B4T_D7;\n";
echo "  background: $B4T_b23". "80;\n";
echo "}\n";
echo "\n";
echo ".token.number,\n";
echo ".token.atrule,\n";
echo ".token.attr-value,\n";
echo ".token.keyword {\n";
echo "  color: $B4T_B8;\n";
echo "}\n";
echo "\n";
echo ".token.function,\n";
echo ".token.class-name {\n";
echo "  color: $B4T_C8;\n";
echo "}\n";
echo "\n";
echo ".token.regex,\n";
echo ".token.important,\n";
echo ".token.variable {\n";
echo "  color: $B4T_D9;\n";
echo "}\n";
echo "\n";
echo ".token.important,\n";
echo ".token.bold {\n";
echo "  font-weight: bold;\n";
echo "}\n";
echo ".token.italic {\n";
echo "  font-style: italic;\n";
echo "}\n";
echo "\n";
echo ".token.entity {\n";
echo "  cursor: help;\n";
echo "}\n";
echo "\n";
echo "pre[data-line] {\n";
echo "  position: relative;\n";
echo "  padding: 1em 0 1em 3em;\n";
echo "}\n";
echo "\n";
echo ".line-highlight {\n";
echo "  position: absolute;\n";
echo "  left: 0;\n";
echo "  right: 0;\n";
echo "  padding: 0;\n";
echo "  margin-top: 1em; /* Same as .prism’s padding-top */\n";
echo "  background: $B4T_b13" . "54;\n";
echo "  background: linear-gradient(to right, $B4T_b13" . "54 70%, $B4T_b13" . "00);\n";
echo "  pointer-events: none;\n";
echo "\n";
echo "  line-height: inherit;\n";
echo "  white-space: pre;\n";
echo "}\n";
echo "\n";
echo ".line-highlight:before,\n";
echo ".line-highlight[data-end]:after {\n";
echo "  content: attr(data-start);\n";
echo "  position: absolute;\n";
echo "  top: .4em;\n";
echo "  left: .6em;\n";
echo "  min-width: 1em;\n";
echo "  padding: 0 .5em;\n";
echo "  background-color: $B4T_b13" . "54;\n";
echo "  color: $B4T_b19;\n";
echo "  font: bold 65%/1.5 sans-serif;\n";
echo "  text-align: center;\n";
echo "  vertical-align: .3em;\n";
echo "  border-radius: 999px;\n";
echo "  box-shadow: 0 1px white;\n";
echo "}\n";
echo "\n";
echo ".line-highlight[data-end]:after {\n";
echo "  content: attr(data-end);\n";
echo "  top: auto;\n";
echo "  bottom: .4em;\n";
echo "}\n";
echo "\n";
echo ".line-numbers .line-highlight:before,\n";
echo ".line-numbers .line-highlight:after {\n";
echo "  content: none;\n";
echo "}\n";
echo "\n";
echo "pre[class*='language-'].line-numbers {\n";
echo "  position: relative;\n";
echo "  padding-left: 3.8em;\n";
echo "  counter-reset: linenumber;\n";
echo "}\n";
echo "\n";
echo "pre[class*='language-'].line-numbers > code {\n";
echo "  position: relative;\n";
echo "  white-space: inherit;\n";
echo "}\n";
echo "\n";
echo ".line-numbers .line-numbers-rows {\n";
echo "  position: absolute;\n";
echo "  pointer-events: none;\n";
echo "  top: -3px;\n";
echo "  font-size: 100%;\n";
echo "  left: -3.8em;\n";
echo "  width: 3em; /* works for line-numbers below 1000 lines */\n";
echo "  letter-spacing: -1px;\n";
echo "  border-right: 1px solid $B4T_b17;\n";
echo "\n";
echo "  -webkit-user-select: none;\n";
echo "  -moz-user-select: none;\n";
echo "  -ms-user-select: none;\n";
echo "  user-select: none;\n";
echo "\n";
echo "}\n";
echo "\n";
echo ".line-numbers-rows > span {\n";
echo "  pointer-events: none;\n";
echo "  display: block;\n";
echo "  counter-increment: linenumber;\n";
echo "}\n";
echo "\n";
echo ".line-numbers-rows > span:before {\n";
echo "  content: counter(linenumber);\n";
echo "  color: $B4T_b14;\n";
echo "  display: block;\n";
echo "  padding-right: 0.8em;\n";
echo "  text-align: right;\n";
echo "}\n";

